version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend-network
    secrets:
      - db-password
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_DATABASE: example
    secrets:
      - db-password
    networks:
      - backend-network
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"  # Correct port mapping for MySQL

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-network
    ports:
      - "80:80" 
    depends_on:
      - backend

networks:
  backend-network:
    driver: bridge
  proxy-network:
    driver: bridge
volumes:
  db-data:

secrets:
  db-password:
    file: db-password