apiVersion: v1
kind: Service

metadata:
  name: my-app-service
  namespace: default

spec:
  selector:
    name: my-app
  
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80

  type: ClusterIP