apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest  # Example image
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"  # Minimum amount of memory requested
            cpu: "250m"     # Minimum amount of CPU requested
          limits:
            memory: "128Mi" # Maximum amount of memory allowed
            cpu: "500m"     # Maximum amount of CPU allowed