apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  namespace: webapp
  labels:
    app:  backend-dep
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name:  backend-cont
        image:  mohamedezzatii/project_backend:0.0.2
        env:
          - name: DB_HOST
            value: "db"
          - name: DB_NAME
            value: "example"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "0244"
          - name: DB_PORT
            value: "3306"
        ports:
        - containerPort:  8000
          name:  backend-port
          protocol: TCP