apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-deployment
  namespace: webapp
  labels:
    app:  backend-deployment
spec:
  selector:
    matchLabels:
      app: backend-pod
  replicas: 2
  template:
    metadata:
      labels:
        app:  backend-pod
    spec:
      containers:
      - name:  backend-cont
        image:  mohamedezzatii/project_backend
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8000
          name:  backend-port