apiVersion: apps/v1
kind: Deployment
metadata:
  name:  proxy
  namespace: webapp
  labels:
    app:  proxy-deb
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 2
  template:
    metadata:
      labels:
        app:  proxy
    spec:
      containers:
      - name:  proxy-cont
        image:  mohamedezzatii/project_proxy:0.0.2
        ports:
        - containerPort:  80
          name:  proxy-port
          protocol: TCP