apiVersion: v1
kind: Service
metadata:
  name: backend-db-service
  namespace: webapp
spec:
  selector: 
    app:  backend-deployment
  type: ClusterIP
  ports:
  - name: backend-port
    port: 8000
    targetPort: 8000