apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: webapp
  labels:
    app: backend
spec:
  selector: 
    app: backend
  type: ClusterIP
  ports:
  - name: backend
    protocol: TCP
    port: 8000
    targetPort: 8000