apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: webapp
  labels:
    app: db
spec:
  selector:
    app:  db
  type: ClusterIP
  ports:
  - name: db
    protocol: TCP
    port: 3306
    targetPort: 3306