apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: webapp
spec:
  selector:
    app:  db-deployment
  type: ClusterIP
  ports:
  - name: db-service
    protocol: TCP
    port: 3306
    targetPort: 3306