apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: webapp
  labels:
    app: proxy
spec:
  selector:
    app:  proxy
  type: NodePort
  ports:
  - name: nodeport-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001