apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: webapp
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/mysql"